//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainCommander.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public int status { get; set; }
        public string id_user { get; set; }
        public int id_supertrip { get; set; }
        public int quantity { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual SuperTrip SuperTrip { get; set; }
    }
}
