//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class langage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langage() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainCommander.Resources.langage", typeof(langage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A propos.
        /// </summary>
        public static string aboutUs {
            get {
                return ResourceManager.GetString("aboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez accepter les conditions !.
        /// </summary>
        public static string acceptCondition {
            get {
                return ResourceManager.GetString("acceptCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout Droits Réservés.
        /// </summary>
        public static string allRight {
            get {
                return ResourceManager.GetString("allRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout les trains.
        /// </summary>
        public static string allTrain {
            get {
                return ResourceManager.GetString("allTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrivée.
        /// </summary>
        public static string arrival {
            get {
                return ResourceManager.GetString("arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrivée à.
        /// </summary>
        public static string arrivalItem {
            get {
                return ResourceManager.GetString("arrivalItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TROUVEZ UN TRAIN.
        /// </summary>
        public static string bannerBtn {
            get {
                return ResourceManager.GetString("bannerBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir son train.
        ///Rapidement et pas cher..
        /// </summary>
        public static string bannerTitle {
            get {
                return ResourceManager.GetString("bannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à aaaaa.
        /// </summary>
        public static string bannerTxt {
            get {
                return ResourceManager.GetString("bannerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer et procéder au payement.
        /// </summary>
        public static string buy {
            get {
                return ResourceManager.GetString("buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panier.
        /// </summary>
        public static string cart {
            get {
                return ResourceManager.GetString("cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prendre cet aller.
        /// </summary>
        public static string chooseOneWay {
            get {
                return ResourceManager.GetString("chooseOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prendre ce retour.
        /// </summary>
        public static string chooseReturn {
            get {
                return ResourceManager.GetString("chooseReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code est invalide.
        /// </summary>
        public static string codeInvalid {
            get {
                return ResourceManager.GetString("codeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le code est requis.
        /// </summary>
        public static string codeRequired {
            get {
                return ResourceManager.GetString("codeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commande.
        /// </summary>
        public static string command {
            get {
                return ResourceManager.GetString("command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe et le mot de passe de confirmation ne correspondent pas.
        /// </summary>
        public static string comparePasswordInvalid {
            get {
                return ResourceManager.GetString("comparePasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez toute vos informations.
        /// </summary>
        public static string confirmationTxt {
            get {
                return ResourceManager.GetString("confirmationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contactez-Nous.
        /// </summary>
        public static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut convallis erat. Donec turpis urna, molestie in ornare sed,.
        /// </summary>
        public static string dc {
            get {
                return ResourceManager.GetString("dc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer tout le panier.
        /// </summary>
        public static string deleteAll {
            get {
                return ResourceManager.GetString("deleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aller le.
        /// </summary>
        public static string depart {
            get {
                return ResourceManager.GetString("depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Départ.
        /// </summary>
        public static string departure {
            get {
                return ResourceManager.GetString("departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Départ à.
        /// </summary>
        public static string departureItem {
            get {
                return ResourceManager.GetString("departureItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut convallis erat. Donec turpis urna, molestie in ornare sed, fermentum et sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi posuere dignissim nisl fringilla maximus. Maecenas rutrum pellentesque mollis. Proin gravida diam ac urna mattis, consectetur volutpat lectus sodales. Donec aliquam dictum lobortis. Suspendisse arcu lacus, eleifend a sagittis ac, bibendum non sem..
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trajet direct.
        /// </summary>
        public static string directPath {
            get {
                return ResourceManager.GetString("directPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse EMail.
        /// </summary>
        public static string eMail {
            get {
                return ResourceManager.GetString("eMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse eMail n&apos;est pas valide.
        /// </summary>
        public static string eMailInvalid {
            get {
                return ResourceManager.GetString("eMailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;adresse eMail est requise.
        /// </summary>
        public static string eMailRequired {
            get {
                return ResourceManager.GetString("eMailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur dans le payement veuillez reessayer..
        /// </summary>
        public static string errorPayment {
            get {
                return ResourceManager.GetString("errorPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Questions Fréquemment Posés.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous ne trouvez pas votre gare essayez avec le nom de la ville. Plus de 30000 ville sont enregistré dans notre service la votre y est surement aussi..
        /// </summary>
        public static string faqText1 {
            get {
                return ResourceManager.GetString("faqText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je ne trouve pas ma gare.
        /// </summary>
        public static string faqTitle1 {
            get {
                return ResourceManager.GetString("faqTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherchez.
        /// </summary>
        public static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prenom.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En cochant cette case, je reconnais avoir pris connaissance des Conditions Générales de Vente SNCF, ainsi que des Conditions Générales de Vente et d&apos;Utilisation du train-commander.fr et je les accepte..
        /// </summary>
        public static string generalCondition {
            get {
                return ResourceManager.GetString("generalCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payer avec paypal.
        /// </summary>
        public static string goToPayment {
            get {
                return ResourceManager.GetString("goToPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez vos options.
        /// </summary>
        public static string how1 {
            get {
                return ResourceManager.GetString("how1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparez les voyages.
        /// </summary>
        public static string how2 {
            get {
                return ResourceManager.GetString("how2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commandez une offre.
        /// </summary>
        public static string how3 {
            get {
                return ResourceManager.GetString("how3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un compte.
        /// </summary>
        public static string how4 {
            get {
                return ResourceManager.GetString("how4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les Dernières Promotions.
        /// </summary>
        public static string lastPromotions {
            get {
                return ResourceManager.GetString("lastPromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Derniers voyage achetés.
        /// </summary>
        public static string lastTripBuy {
            get {
                return ResourceManager.GetString("lastTripBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se connecter.
        /// </summary>
        public static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre Message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau Mot de Passe.
        /// </summary>
        public static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nouveau Mot de Passe est requis.
        /// </summary>
        public static string newPasswordRequired {
            get {
                return ResourceManager.GetString("newPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aller simple.
        /// </summary>
        public static string oneWayTicket {
            get {
                return ResourceManager.GetString("oneWayTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nos Conditions.
        /// </summary>
        public static string ourConditions {
            get {
                return ResourceManager.GetString("ourConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos Passager.
        /// </summary>
        public static string passenger {
            get {
                return ResourceManager.GetString("passenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de Passe.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confimer le Mot de Passe.
        /// </summary>
        public static string passwordConfirmation {
            get {
                return ResourceManager.GetString("passwordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La confirmation du Mot de Passe est invalide.
        /// </summary>
        public static string passwordConfirmationInvalid {
            get {
                return ResourceManager.GetString("passwordConfirmationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La confirmation du Mot de Passe est requise.
        /// </summary>
        public static string passwordConfirmationRequired {
            get {
                return ResourceManager.GetString("passwordConfirmationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de Passe invalide.
        /// </summary>
        public static string passwordInvalid {
            get {
                return ResourceManager.GetString("passwordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de Passe requis.
        /// </summary>
        public static string passwordRequired {
            get {
                return ResourceManager.GetString("passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trajet.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trajet via.
        /// </summary>
        public static string pathThrough {
            get {
                return ResourceManager.GetString("pathThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nouveau site internet vous permettant de commander un train comme jamais.
        /// </summary>
        public static string pressCitation1 {
            get {
                return ResourceManager.GetString("pressCitation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couverture Mediatique.
        /// </summary>
        public static string pressCoverage {
            get {
                return ResourceManager.GetString("pressCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Imprimez votre billet.
        /// </summary>
        public static string printTicket {
            get {
                return ResourceManager.GetString("printTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Promotions.
        /// </summary>
        public static string promos {
            get {
                return ResourceManager.GetString("promos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous allez recoir un email pour votre ticket.
        ///Vous pouvez aussi imprimer votre ticket maintenant :.
        /// </summary>
        public static string receiveMailCanPrint {
            get {
                return ResourceManager.GetString("receiveMailCanPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;inscrire.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se souvenir du navigateur.
        /// </summary>
        public static string rememberBrowser {
            get {
                return ResourceManager.GetString("rememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se souvenir de moi.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se souvenir du Mot de Passe .
        /// </summary>
        public static string rememberPassword {
            get {
                return ResourceManager.GetString("rememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réservation.
        /// </summary>
        public static string reserv {
            get {
                return ResourceManager.GetString("reserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reservez un billet de train.
        /// </summary>
        public static string reserveTitle {
            get {
                return ResourceManager.GetString("reserveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retourner à votre panier.
        /// </summary>
        public static string returnCart {
            get {
                return ResourceManager.GetString("returnCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour le.
        /// </summary>
        public static string returnId {
            get {
                return ResourceManager.GetString("returnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aller retour.
        /// </summary>
        public static string roundTrip {
            get {
                return ResourceManager.GetString("roundTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer le panier.
        /// </summary>
        public static string saveCart {
            get {
                return ResourceManager.GetString("saveCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Envoyer.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les Villes Les Plus Sollicités.
        /// </summary>
        public static string statisticTitle {
            get {
                return ResourceManager.GetString("statisticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ut convallis erat. Donec turpis urna, molestie in ornare sed,.
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre commande est un succès.
        /// </summary>
        public static string sucessPay {
            get {
                return ResourceManager.GetString("sucessPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je Prends Ma Place.
        /// </summary>
        public static string takePlace {
            get {
                return ResourceManager.GetString("takePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Numéro de Telephone.
        /// </summary>
        public static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conditions d&apos;Utilisation.
        /// </summary>
        public static string termsUse {
            get {
                return ResourceManager.GetString("termsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remplissez notre formulaire selon vos souhaits.
        /// </summary>
        public static string textHow1 {
            get {
                return ResourceManager.GetString("textHow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plusieurs trajets en fonctions de vos options seront proposés. Choisissez celui que vous préférez.
        /// </summary>
        public static string textHow2 {
            get {
                return ResourceManager.GetString("textHow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;offre choisis se trouve dans votre panier. Suivez les étapes pour finaliser votre commande.
        /// </summary>
        public static string textHow3 {
            get {
                return ResourceManager.GetString("textHow3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer un compte vous permettra de suivre vos commandes et de pouvoir faire des modifications sur vos voyages.
        /// </summary>
        public static string textHow4 {
            get {
                return ResourceManager.GetString("textHow4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voyage.
        /// </summary>
        public static string trip {
            get {
                return ResourceManager.GetString("trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VOIR TOUTE NOS PROMOTIONS.
        /// </summary>
        public static string viewPromotion {
            get {
                return ResourceManager.GetString("viewPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je le veux.
        /// </summary>
        public static string wantIt {
            get {
                return ResourceManager.GetString("wantIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qu&apos;est-ce que Train Commander ?.
        /// </summary>
        public static string whatIs {
            get {
                return ResourceManager.GetString("whatIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos Informations.
        /// </summary>
        public static string yourInformations {
            get {
                return ResourceManager.GetString("yourInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos Voyages.
        /// </summary>
        public static string yourTrip {
            get {
                return ResourceManager.GetString("yourTrip", resourceCulture);
            }
        }
    }
}
